package com.interviewbuddy.domain;

public enum Topic {
    JAVA_CORE, COLLECTIONS, CONCURRENCY, JVM_INTERNALS,
    SPRING_BOOT, SPRING_SECURITY, HIBERNATE_JPA, MICROSERVICES,
    DESIGN_PATTERNS, SOLID, TDD, SYSTEM_DESIGN, BEHAVIOURAL
}
